FROM jacobrosenthal/balena-lighthouse-ethereum:latest

# Defines our working directory in container
RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app

RUN echo "LABEL=STORAGE /mnt/storage ext4 rw,noatime,data=ordered 0 2" >> /etc/fstab

# This will copy all files in our root to the working  directory in the container
COPY ./app ./

CMD ["bash", "/usr/src/app/start.sh"]
