
version: '2'
services:
  # hns:
  #   build: ./balena-hns
  #   restart: unless-stopped
  #   ports:
  #     - "13037:13037"
  #     - "13039:13039"
  #   devices:
  #     - "/dev/sda3:/dev/sda3"
  #   cap_add:
  #     - SYS_ADMIN
  geth:
    build: ./balena-geth
    restart: unless-stopped
    ports:
      - "8545:8545" #rpc api
      - "8546:8546" #ws api
    devices:
      - "/dev/sda1:/dev/sda1"
    cap_add:
      - SYS_ADMIN
  0x_mesh:
    build: ./balena-0x_mesh
    restart: unless-stopped
    ports:
      - "60557:60557"
      - "60558:60558"
      - "60559:60559"
    depends_on:
      - "geth"
    devices:
      - "/dev/sda4:/dev/sda4"
    cap_add:
      - SYS_ADMIN
  beacon:
    build: ./balena-lighthouse
    restart: unless-stopped
    ports:
      - "5052" #http api
      - "5053" #ws api
    depends_on:
      - "geth"
    devices:
      - "/dev/sda2:/dev/sda2"
    cap_add:
      - SYS_ADMIN
  validator:
    build: ./balena-lighthouse-validator
    restart: unless-stopped
    depends_on:
      - "beacon"
    devices:
      - "/dev/sda6:/dev/sda6"
    cap_add:
      - SYS_ADMIN
  rust:
    build: ./balena-rust
    restart: unless-stopped
    privileged: true # overkill for /dev/sda
    labels:
      io.balena.features.balena-socket: 'true'
