
version: '2'
services:
  # hns:
  #   build: ./balena-hns
  #   restart: always
  #   ports:
  #     - "13037:13037"
  #   # overkill for /dev/sda
  #   privileged: true
  parity:
    build: ./balena-parity
    restart: always
    ports:
      - "8545:8545"
    # overkill for /dev/sda
    privileged: true
    environment:
      #not necessary to pass balena vars explicitly, but good for documentation
      - BALENAENV_PARITY_CORS
