FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:latest-build

# Defines our working directory in container
RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app

RUN install_packages git

RUN git clone https://github.com/handshake-org/hsd.git && \
        cd hsd && \
        JOBS=MAX npm install --production --unsafe-perm && \
        npm cache clean --force && \
        rm -rf /tmp/*

CMD ["node", "/usr/src/app/hsd/bin/hsd", "--no-auth"]
